name: Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  changes:
    name: File Change Filter
    runs-on: ubuntu-latest
    outputs:
      back-end: ${{ steps.filter.outputs.back-end }}
      front-end: ${{ steps.filter.outputs.front-end }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          back-end:
            - 'back-end/**'
          front-end:
            - 'front-end/**'
          allChanges:
            - added|deleted|modified: '**'

  simple_lambda_test:
    name: Simple Lambda Test
    needs: changes
    if: ${{ needs.changes.outputs.back-end == 'true' }}
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./back-end/lambda

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install boto3 For Simple Test
        run: pip3 install boto3

      - name: Run Unit Test
        run: python test_simple_visit_count_lambda_function.py

  mock_lambda_test:
    name: Mock Lambda Test
    needs: changes
    if: ${{ needs.changes.outputs.back-end == 'true' }}
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./back-end/lambda

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install boto3 For Simple Test
        run: pip3 install boto3

      - name: Run Mock Test
        run: python test_comprehensive_visit_count_lambda_function.py

  terraform_plan:
    name: Terraform Plan
    
    needs:
      - changes
      - simple_lambda_test
      - mock_lambda_test
    if: github.event_name == 'pull_request' && needs.changes.outputs.back-end == 'true'
    
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      EXPAND_SUMMARY_DETAILS: true
      TF_WORKSPACE: default # change for matrix runs

    defaults:
      run:
        working-directory: ./back-end/infra
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive -diff
        continue-on-error: true

      - name: Post Format Comment
        if: ${{ always() && (steps.fmt.outcome == 'success' || steps.fmt.outcome == 'failure') }}
        uses: GetTerminus/terraform-pr-commenter@v3
        with:
          commenter_type: fmt
          commenter_input: ${{ format('{0}{1}', steps.fmt.outputs.stdout, steps.fmt.outputs.stderr) }}
          commenter_exitcode: ${{ steps.fmt.outputs.exitcode }}

      - name: Terraform Init
        id: init
        run: terraform init -input=false
      
      - name: Post Init Comment
        if: ${{ always() && (steps.init.outcome == 'success' || steps.init.outcome == 'failure') }}
        uses: GetTerminus/terraform-pr-commenter@v3
        with:
          commenter_type: init
          commenter_input: ${{ format('{0}{1}', steps.init.outputs.stdout, steps.init.outputs.stderr) }}
          commenter_exitcode: ${{ steps.init.outputs.exitcode }}

      - name: Terraform Validate
        id: validate
        run: terraform validate
      
      - name: Post TF Validate Comment
        if: ${{ always() && (steps.validate.outcome == 'success' || steps.validate.outcome == 'failure') }}
        uses: GetTerminus/terraform-pr-commenter@v3
        with:
          commenter_type: validate
          commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
          commenter_exitcode: ${{ steps.validate.outputs.exitcode }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false |& tee tf_plan.txt 

      - name: Post TF Plan Comment
        uses: GetTerminus/terraform-pr-commenter@v3
        with:
          commenter_type: plan
          commenter_plan_path: infra/tf_plan.txt
          commenter_exitcode: ${{ steps.plan.outputs.exitcode }}

  terraform_apply:
    name: Terraform Apply
   
    needs:
      - changes
      - simple_lambda_test
      - mock_lambda_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changes.outputs.back-end == 'true'
    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end/infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init -input=false
      
      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        id: apply
        run: |
          terraform apply --auto-approve
          
      - name: Change Dir
        id: dir
        run: |
          cd ../scripts

      - name: Inject API
        id: inject
        run: |
          bash api-injector.sh

  sync_s3:
    name: Sync S3
    needs: 
      - changes
      - terraform_apply
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changes.outputs.front-end == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Upload Files To S3 Bucket
        run: aws s3 sync . s3://billy-euceda.com --delete
